---
- name: Install some required packages from apt
  apt:
      name={{ item }} state=installed
  with_items:
    - mysql-client
    - mysql-server
    - mysql-common
    - libmysqlclient-dev
    - python-mysqldb
    - xvfb
    - r-base
  sudo: true
- name: Install a few R packages
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{item}}' %in% installed.packages()[,'Package'])) install.packages(pkgs='{{item}}', repos=c('http://www.freestatistics.org/cran/'))"
  with_items:
    - argparse
  sudo: true
- name: Start the MySQL service
  sudo: yes
  service:
    name: mysql
    state: started
    enabled: true
- name: Update mysql root password for all root accounts
  sudo: yes
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    login_user=root
    login_password={{ mysql_root_password }}
    check_implicit_admin=yes
    priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - '%'
- name: Copy sciluigi_usecase project folder to host
  copy:
      src=files/proj
      dest=/home/ubuntu
      mode=0644
- name: Make openjupyter script executable
  file:
      path=/home/ubuntu/proj/largescale_svm/openjupyter.sh
      mode=744
- name: Make runall script executable
  file:
      path=/home/ubuntu/proj/largescale_svm/runall.sh
      mode=744
- name: Place "Open Jupyter Notebook" icon on desktop
  copy:
      src=files/open_jupyter_notebook.desktop
      dest=/home/ubuntu/Desktop
      mode=744
- name: Download executable files from FigShare, for use in the workflow
  get_url: url=https://ndownloader.figshare.com/files/6330402 dest=/home/ubuntu/proj/largescale_svm/binaries.tar.gz
- name: Create bin folder
  file: name=/home/ubuntu/proj/largescale_svm/bin state=directory
- name: Untar binariesarchive
  unarchive: src=/home/ubuntu/proj/largescale_svm/binaries.tar.gz dest=/home/ubuntu/proj/largescale_svm/bin copy=no
